services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: datasuperior/hive:latest
    environment:
      DB_DRIVER: postgres
      IS_RESUME: "true"
      SERVICE_NAME: "metastore"
      HIVE_METASTORE_DB_TYPE: "postgres"
      HIVE_METASTORE_USER: "hiveuser"
      HIVE_METASTORE_PASSWORD: "hivepassword"
      HIVE_METASTORE_URL: "jdbc:postgresql://postgres:5432/metastore_db"
      HIVE_CONF_DIR: "/opt/hive/conf"
    depends_on:
      - postgres
    ports:
      - "9083:9083"
      - "10000:10000"
    volumes:
      - hive_metastore_data:/opt/hive-metastore
      - ./configs/hive:/opt/hive/conf

  trino:
    image: 'trinodb/trino:457'
    hostname: trino
    depends_on:
      - hive-metastore
    ports:
      - '8080:8080'
    volumes:
      - ./configs/etc:/etc/trino
      - ./configs/hive/hive-site.xml:/etc/hadoop/conf/metastore-site.xml

  trino-init:
    image: 'trinodb/trino:457'
    depends_on:
      - trino
    volumes:
      - ./configs/etc:/docker-entrypoint-initdb.d
    entrypoint: ["/bin/sh", "-c", "/docker-entrypoint-initdb.d/wait-and-run.sh"]

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-client:
    image: minio/mc:RELEASE.2024-10-08T09-37-26Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do sleep 2; done;
      /usr/bin/mc mb myminio/hive --ignore-existing;
      /usr/bin/mc policy set public myminio/hive;
      /usr/bin/mc mb myminio/staging --ignore-existing;
      /usr/bin/mc policy set public myminio/staging;
      sleep 3600;
      "

volumes:
  postgres_data:
  hive_metastore_data:
  minio_data:
